// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zugpqdenystyxerorggo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1Z3BxZGVueXN0eXhlcm9yZ2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTY5OTYsImV4cCI6MjA2NTQ5Mjk5Nn0.M7mVBHDzHWWICtWoiCzjAmZWdhdMJNIfXsuHzB6LFwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);